blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/grafana/tilt-extensions/discussions
    about: Ask questions and share ideas with the community
  - name: Security Issue
    url: https://github.com/grafana/tilt-extensions/security/policy
    about: Report security vulnerabilities in a private manner
