image:
  repository:
    grafana/grafana
  tag:
    ops-plugins
persistence:
  enabled: false
sidecar:
  datasources:
    enabled: true
grafana.ini:
  app_mode: development
  analytics:
    reporting_enabled: false
  auth.anonymous:
  #  enabled: true
    org_role: Admin
  security:
    admin_user: admin
    admin_password: admin
  feature_toggles:
    enable: topnav
  log:
    level: info
  log.frontend:
    enabled: true
  navigation.app_sections:
    grafana-incident-app: alerts-and-incidents
  plugins:
    allow_loading_unsigned_plugins: grafana-incident-app
  server:
    http_port: 3000
    router_logging: true
  users:
    default_theme: dark