apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.plugin_name }}-ui
  labels:
    app.kubernetes.io/component: {{ .Values.plugin_name }}-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.plugin_name }}-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.plugin_name }}-ui
    spec:
      containers:
        - name: {{ .Values.plugin_name }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: Always
          args: {{- .Values.ui.args | toYaml | nindent 12 }}
          securityContext: {{- .Values.ui.securityContext | toYaml | nindent 12 }}
          env:
            {{- range $key, $value := .Values.ui.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts: {{- .Values.ui.volumeMounts | toYaml | nindent 12 }}
      volumes: {{- .Values.ui.volumes | toYaml | nindent 8 }}
