def post_build(name, resource, target_resource, labels=[]):
    local_resource(
        name,
        labels=labels,
        serve_cmd=["./post_build.sh", resource, target_resource],
    )                
